environments:
  - home-pc
  - home-laptop
  - arista-laptop
  - arista-server
  - raspberry-pi

globals:
  is_work: {{ or (eq .Environment "arista-laptop") (eq .Environment "arista-server") }}
  models:
    "gemma4-64k": { name: "Gemma 4 26B", ctx: 64000, max_output: 8192 }
    "qwen3.5:35b": { name: "Qwen 3.5 35B", ctx: 32768, max_output: 4096 }
    "qwen3.6:27b-q4_K_M": { name: "Qwen 3.6 27B Q4_K_M", ctx: 131072, max_output: 4096 }
    "qwen3.6:35b-q4_K_M": { name: "Qwen 3.6 35B Q4_K_M", ctx: 32768, max_output: 4096 }

apps:
  antigravity:
    enabled: {{ or (eq .Environment "home-pc") (eq .Environment "home-laptop") }}
  nvim:
    enabled: {{ ne .Environment "raspberry-pi" }}
  pi-harness:
    enabled: {{ eq .Environment "home-pc" }}
  vim:
    enabled: {{ ne .Environment "raspberry-pi" }}
  zellij:
    enabled: true
    vars:
      ai_budget_enabled: {{ or (eq .Environment "arista-laptop") (eq .Environment "arista-server") }}
